# Generated by Django 5.0.6 on 2024-05-22 06:53

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tanks', 'Танки'), ('Hills', 'Хилы'), ('DD', 'ДД'), ('Sellers', 'Торговцы'), ('Gildmasters', 'Гилдмастеры'), ('Kwestgiver', 'Квестгиверы'), ('Blacksmith', 'Кузнецы'), ('Tanner', 'Кожевники'), ('Potion master', 'Зельевары'), ('Spell master', 'Мастера заклинаний')], default='Tanks', help_text='категория', max_length=30)),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(help_text='заголовок', max_length=255, unique=True)),
                ('description', models.TextField(help_text='текст')),
                ('mediaoforder', ckeditor_uploader.fields.RichTextUploadingField(default=None, null=True)),
                ('author', models.ForeignKey(help_text='автор', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отклика')),
                ('accepted', models.BooleanField(default=None, null=True, verbose_name='Принять отклик')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ads.post', verbose_name='Объявление')),
            ],
        ),
    ]
